vim.keymap.set("n", "<Leader>ff", "<cmd>Telescope find_files<cr>")
vim.keymap.set("n", "<Leader>fg", "<cmd>Telescope live_grep<cr>")
vim.keymap.set("n", "<Leader>fb", "<cmd>Telescope buffers<cr>")
vim.keymap.set("n", "<Leader>fo", "<cmd>Telescope oldfiles<cr>")
vim.keymap.set("n", "<Leader>fh", "<cmd>Telescope help_tags<cr>")
vim.keymap.set("n", "<Leader>fr", "<cmd>Telescope lsp_references<cr>")
vim.keymap.set("n", "<Leader>fd", "<cmd>Telescope lsp_definitions<cr>")
vim.keymap.set("n", "<Leader>fa", "<cmd>Telescope lsp_definitions<cr>")
